#define NUM_NEURONS 10
#define NUM_INPUTS 4
#define NUM_OUTPUTS 3
#define NUM_SYNAPSES_PER_NEURON 5
#define THRESHOLD 0
#define LEARNING_RATE 0.01
#define ACTIVITY_DISCOUNT_FACTOR 0.85
#define MIN_START_WEIGHT -0.33